version: '3.8'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: messenger-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"